t = {
            "alias": "",
            "auctionEndTime": "",
            "baseCcy": "SKY",
            "category": "1",
            "contTdSwTime": "1757595600000",
            "ctMult": "",
            "ctType": "",
            "ctVal": "",
            "ctValCcy": "",
            "expTime": "",
            "futureSettlement": False,
            "instFamily": "",
            "instId": "SKY-USD",
            "instIdCode": 226626,
            "instType": "SPOT",
            "lever": "",
            "listTime": "1757592000000",
            "lotSz": "0.1",
            "maxIcebergSz": "",
            "maxLmtAmt": "20000000",
            "maxLmtSz": "9999999999999999",
            "maxMktAmt": "1000000",
            "maxMktSz": "1000000",
            "maxStopSz": "1000000",
            "maxTriggerSz": "",
            "maxTwapSz": "",
            "minSz": "100",
            "openType": "pre_quote",
            "optType": "",
            "preMktSwTime": "",
            "quoteCcy": "USD",
            "ruleType": "normal",
            "settleCcy": "",
            "state": "preopen",
            "stk": "",
            "tickSz": "0.00001",
            "tradeQuoteCcyList": [
                "USDG",
                "USD",
                "USDC"
            ],
            "uly": ""
        }

fut = {
            "alias": "this_week",
            "auctionEndTime": "",
            "baseCcy": "",
            "category": "1",
            "contTdSwTime": "",
            "ctMult": "1",
            "ctType": "inverse",
            "ctVal": "100",
            "ctValCcy": "USD",
            "expTime": "1757664000000",
            "futureSettlement": True,
            "instFamily": "BTC-USD",
            "instId": "BTC-USD-250912",
            "instIdCode": 225334,
            "instType": "FUTURES",
            "lever": "20",
            "listTime": "1756455000524",
            "lotSz": "1",
            "maxIcebergSz": "1000000.0000000000000000",
            "maxLmtAmt": "20000000",
            "maxLmtSz": "1000000",
            "maxMktAmt": "",
            "maxMktSz": "10000",
            "maxStopSz": "10000",
            "maxTriggerSz": "1000000.0000000000000000",
            "maxTwapSz": "1000000.0000000000000000",
            "minSz": "1",
            "openType": "",
            "optType": "",
            "preMktSwTime": "",
            "quoteCcy": "",
            "ruleType": "normal",
            "settleCcy": "BTC",
            "state": "live",
            "stk": "",
            "tickSz": "0.1",
            "tradeQuoteCcyList": [],
            "uly": "BTC-USD"
        }

print(list(fut.keys()))