# Generated by Django 5.2.3 on 2025-07-22 13:34

import charts.models.crypto_bybit_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentBybit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('baseCoin', models.CharField(max_length=50)),
                ('quoteCoin', models.CharField(max_length=50)),
                ('hasFutures', models.BooleanField(default=False)),
                ('hasSpot', models.BooleanField(default=False)),
                ('hasOption', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'baseCoin', 'quoteCoin'], name='charts_inst_symbol_cedae6_idx')],
            },
        ),
        migrations.CreateModel(
            name='InfoBybitSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('marginTrading', models.CharField(max_length=50)),
                ('stTag', models.CharField(max_length=50)),
                ('lotSizeFilter', models.JSONField()),
                ('priceFilter', models.JSONField()),
                ('riskParameters', models.JSONField()),
                ('inst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot_bybit', to='charts.instrumentbybit')),
            ],
        ),
        migrations.CreateModel(
            name='InfoBybitFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('launchTime', models.CharField(max_length=50)),
                ('deliveryTime', models.CharField(blank=True, max_length=50)),
                ('deliveryFeeRate', models.CharField(max_length=50)),
                ('priceScale', models.CharField(max_length=50)),
                ('unifiedMarginTrade', models.BooleanField()),
                ('fundingInterval', models.IntegerField()),
                ('settleCoin', models.CharField(max_length=50)),
                ('copyTrading', models.CharField(max_length=50)),
                ('upperFundingRate', models.CharField(max_length=50)),
                ('lowerFundingRate', models.CharField(max_length=50)),
                ('isPreListing', models.BooleanField()),
                ('preListingInfo', models.CharField(blank=True, max_length=50, null=True)),
                ('displayName', models.CharField(blank=True, max_length=50, null=True)),
                ('leverageFilter', models.JSONField()),
                ('priceFilter', models.JSONField()),
                ('lotSizeFilter', models.JSONField()),
                ('riskParameters', models.JSONField()),
                ('inst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='futures_bybit', to='charts.instrumentbybit')),
            ],
        ),
        migrations.CreateModel(
            name='InfoBybitOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('settleCoin', models.CharField(max_length=50)),
                ('optionsType', models.CharField(max_length=50)),
                ('launchTime', models.CharField(max_length=50)),
                ('deliveryTime', models.CharField(max_length=50)),
                ('deliveryFeeRate', models.CharField(max_length=50)),
                ('displayName', models.CharField(max_length=50)),
                ('priceFilter', models.JSONField()),
                ('lotSizeFilter', models.JSONField()),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_bybit', to='charts.instrumentbybit')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'optionsType'], name='charts_info_symbol_3703dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataByBitSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.IntegerField(unique=True)),
                ('end_date', models.IntegerField(unique=True)),
                ('interval', models.CharField(max_length=50)),
                ('data', models.FileField(upload_to=charts.models.crypto_bybit_models.historical_data_spot_dir_path)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_spot_data', to='charts.instrumentbybit')),
            ],
            options={
                'indexes': [models.Index(fields=['start_date', 'end_date', 'interval'], name='charts_hist_start_d_1aa670_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataByBitFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.IntegerField(unique=True)),
                ('end_date', models.IntegerField(unique=True)),
                ('interval', models.CharField(max_length=50)),
                ('data', models.FileField(upload_to=charts.models.crypto_bybit_models.historical_data_futures_dir_path)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_futures_data', to='charts.instrumentbybit')),
            ],
            options={
                'indexes': [models.Index(fields=['start_date', 'end_date', 'interval'], name='charts_hist_start_d_24ab29_idx')],
            },
        ),
    ]
