# Generated by Django 5.2.3 on 2025-06-29 14:20

import charts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentByBitLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('contractType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('baseCoin', models.CharField(max_length=50)),
                ('quoteCoin', models.CharField(max_length=50)),
                ('launchTime', models.CharField(max_length=50)),
                ('deliveryTime', models.CharField(blank=True, max_length=50)),
                ('deliveryFeeRate', models.CharField(max_length=50)),
                ('priceScale', models.CharField(max_length=50)),
                ('unifiedMarginTrade', models.BooleanField()),
                ('fundingInterval', models.IntegerField()),
                ('settleCoin', models.CharField(max_length=50)),
                ('copyTrading', models.CharField(max_length=50)),
                ('upperFundingRate', models.CharField(max_length=50)),
                ('lowerFundingRate', models.CharField(max_length=50)),
                ('isPreListing', models.BooleanField()),
                ('preListingInfo', models.CharField(blank=True, max_length=50, null=True)),
                ('displayName', models.CharField(blank=True, max_length=50, null=True)),
                ('leverageFilter', models.JSONField()),
                ('priceFilter', models.JSONField()),
                ('lotSizeFilter', models.JSONField()),
                ('riskParameters', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'baseCoin', 'quoteCoin'], name='charts_inst_symbol_5a3baf_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataByBitLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('interval', models.CharField(max_length=50)),
                ('data', models.FileField(upload_to=charts.models.historical_data_linear_directory_path)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='charts.instrumentbybitlinear')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentByBitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('baseCoin', models.CharField(max_length=50)),
                ('quoteCoin', models.CharField(max_length=50)),
                ('settleCoin', models.CharField(max_length=50)),
                ('optionsType', models.CharField(max_length=50)),
                ('launchTime', models.CharField(max_length=50)),
                ('deliveryTime', models.CharField(max_length=50)),
                ('deliveryFeeRate', models.CharField(max_length=50)),
                ('displayName', models.CharField(max_length=50)),
                ('priceFilter', models.JSONField()),
                ('lotSizeFilter', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'baseCoin', 'quoteCoin'], name='charts_inst_symbol_a954dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentByBitSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('baseCoin', models.CharField(max_length=50)),
                ('quoteCoin', models.CharField(max_length=50)),
                ('innovation', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('marginTrading', models.CharField(max_length=50)),
                ('stTag', models.CharField(max_length=50)),
                ('lotSizeFilter', models.JSONField()),
                ('priceFilter', models.JSONField()),
                ('riskParameters', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'baseCoin', 'quoteCoin'], name='charts_inst_symbol_0a4c6f_idx')],
            },
        ),
    ]
