# Generated by Django 5.2.3 on 2025-07-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldatabybitfutures',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='historicaldatabybitspot',
            options={'ordering': ['start_date']},
        ),
    ]
