# Generated by Django 5.2.3 on 2025-08-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataBybitInverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.IntegerField()),
                ('openPrice', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('volume', models.FloatField()),
                ('turnover', models.FloatField()),
                ('interval', models.CharField(max_length=10)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_inverse_bybit', to='charts.instrumentbybitinverse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('startTime', 'inst', 'interval'), name='unique_inverse_startTime_inst_interval')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataBybitLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.IntegerField()),
                ('openPrice', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('volume', models.FloatField()),
                ('turnover', models.FloatField()),
                ('interval', models.CharField(max_length=10)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_linear_bybit', to='charts.instrumentbybitspot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('startTime', 'inst', 'interval'), name='unique_linear_startTime_inst_interval')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataBybitSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.IntegerField()),
                ('openPrice', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('volume', models.FloatField()),
                ('turnover', models.FloatField()),
                ('interval', models.CharField(max_length=10)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_spot_bybit', to='charts.instrumentbybitspot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('startTime', 'inst', 'interval'), name='unique_spot_startTime_inst_interval')],
            },
        ),
    ]
