# Generated by Django 5.2.3 on 2025-06-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldatabybitlinear',
            name='end_date',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldatabybitlinear',
            name='start_date',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
