# Generated by Django 5.2.3 on 2025-08-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaldatabybitinverse",
            name="inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hist_data",
                to="charts.instrumentbybitinverse",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldatabybitlinear",
            name="inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hist_data",
                to="charts.instrumentbybitlinear",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldatabybitspot",
            name="inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hist_data",
                to="charts.instrumentbybitspot",
            ),
        ),
    ]
