# Generated by Django 5.2.3 on 2025-08-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_historicaldatabybitinverse_historicaldatabybitlinear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldatabybitinverse',
            name='startTime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldatabybitlinear',
            name='startTime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicaldatabybitspot',
            name='startTime',
            field=models.FloatField(),
        ),
    ]
