# Generated by Django 5.2.3 on 2025-08-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_historicaldatabybitfutures_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldatabybitspot',
            name='end_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicaldatabybitspot',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
