# Generated by Django 5.2.3 on 2025-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_historicaldatabybitlinear_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldatabybitlinear',
            name='end_date',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldatabybitlinear',
            name='start_date',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='historicaldatabybitlinear',
            index=models.Index(fields=['start_date', 'end_date', 'interval'], name='charts_hist_start_d_f010de_idx'),
        ),
    ]
