# Generated by Django 5.2.3 on 2025-08-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0002_alter_historicaldatabybitinverse_inst_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candlebybitinverse",
            name="inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candles",
                to="charts.instrumentbybitinverse",
            ),
        ),
        migrations.AlterField(
            model_name="candlebybitlinear",
            name="inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candles",
                to="charts.instrumentbybitlinear",
            ),
        ),
        migrations.AlterField(
            model_name="candlebybitspot",
            name="inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candles",
                to="charts.instrumentbybitspot",
            ),
        ),
    ]
