# Generated by Django 5.2.3 on 2025-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0003_alter_candlebybitinverse_inst_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candlebybitinverse",
            name="first_candle",
        ),
        migrations.RemoveField(
            model_name="candlebybitinverse",
            name="last_candle",
        ),
        migrations.RemoveField(
            model_name="candlebybitlinear",
            name="first_candle",
        ),
        migrations.RemoveField(
            model_name="candlebybitlinear",
            name="last_candle",
        ),
        migrations.RemoveField(
            model_name="candlebybitspot",
            name="first_candle",
        ),
        migrations.RemoveField(
            model_name="candlebybitspot",
            name="last_candle",
        ),
    ]
