# Generated by Django 5.2.3 on 2025-08-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_historicaldatabybitspot_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldatabybitfutures',
            name='end_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicaldatabybitfutures',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
