# Generated by Django 5.2.3 on 2025-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_historicaldatabybitinverse_starttime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldatabybitinverse',
            options={'ordering': ['startTime']},
        ),
        migrations.AlterModelOptions(
            name='historicaldatabybitlinear',
            options={'ordering': ['startTime']},
        ),
        migrations.AlterModelOptions(
            name='historicaldatabybitspot',
            options={'ordering': ['startTime']},
        ),
        migrations.AddIndex(
            model_name='historicaldatabybitinverse',
            index=models.Index(fields=['startTime'], name='charts_hist_startTi_0f9bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldatabybitlinear',
            index=models.Index(fields=['startTime'], name='charts_hist_startTi_e99c31_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldatabybitspot',
            index=models.Index(fields=['startTime'], name='charts_hist_startTi_fc0193_idx'),
        ),
    ]
