# Generated by Django 5.2.3 on 2025-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0004_remove_candlebybitinverse_first_candle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infookxfutures",
            name="preMktSwTime",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="infookxmargin",
            name="preMktSwTime",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="infookxspot",
            name="preMktSwTime",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="infookxswap",
            name="preMktSwTime",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
