# Generated by Django 5.2.3 on 2025-08-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_alter_historicaldatabybitinverse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldatabybitlinear',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_linear_bybit', to='charts.instrumentbybitlinear'),
        ),
    ]
