# Generated by Django 5.2.3 on 2025-07-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_exchange_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='exchange',
        ),
    ]
