# Generated by Django 5.2.3 on 2025-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_instrumentokx_infookxspot_infookxmargin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infookxmargin',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='auctionEndTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='contTdSwTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='ctMult',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='ctType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='ctVal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='ctValCcy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='expTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='instFamily',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='instType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='lever',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='listTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='lotSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxIcebergSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxLmtAmt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxLmtSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxMktAmt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxMktSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxStopSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxTriggerSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='maxTwapSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='minSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='openType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='optType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='ruleType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='settleCcy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='stk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='tickSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxmargin',
            name='uly',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='auctionEndTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='contTdSwTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='ctMult',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='ctType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='ctVal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='ctValCcy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='expTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='instFamily',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='instType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='lever',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='listTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='lotSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxIcebergSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxLmtAmt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxLmtSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxMktAmt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxMktSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxStopSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxTriggerSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='maxTwapSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='minSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='openType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='optType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='ruleType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='settleCcy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='stk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='tickSz',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='infookxspot',
            name='uly',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
