# Generated by Django 5.2.3 on 2025-07-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_remove_category_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exchanges',
            field=models.ManyToManyField(related_name='categories', to='charts.exchange'),
        ),
    ]
