# Generated by Django 5.2.3 on 2025-09-28 13:57

import django.db.models.deletion
import traders_blog.models.levels_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charts", "0005_infookxfutures_premktswtime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelSpotBybit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="charts.instrumentbybitspot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LevelSpotBybitImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=traders_blog.models.levels_models.image_spot_bybit_path,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="traders_blog.levelspotbybit",
                    ),
                ),
            ],
        ),
    ]
