# Generated by Django 5.2.3 on 2025-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelspotbybit",
            name="levels_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="levelspotbybit",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
