# Generated by Django 5.2.3 on 2025-10-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0005_infookxfutures_premktswtime_and_more"),
        ("traders_blog", "0002_levelspotbybit_levels_date_levelspotbybit_price"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="levelspotbybit",
            index=models.Index(fields=["-price"], name="traders_blo_price_904b95_idx"),
        ),
    ]
