# Generated by Django 5.2.3 on 2025-10-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0003_levelspotbybit_traders_blo_price_904b95_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelsTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="levelspotbybit",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="instruments", to="traders_blog.levelstag"
            ),
        ),
    ]
