# Generated by Django 5.2.3 on 2025-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0004_levelstag_levelspotbybit_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelstag",
            name="slug",
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
