# Generated by Django 5.2.3 on 2025-10-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0005_levelstag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelspotbybit",
            name="title_description",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
