# Generated by Django 5.2.3 on 2025-10-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0006_levelspotbybit_title_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelspotbybit",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="levelspotbybit",
            name="exchange",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
