# Generated by Django 5.2.3 on 2025-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0007_levelspotbybit_category_levelspotbybit_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelspotbybit",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
