# Generated by Django 5.2.3 on 2025-10-21 19:08

import django.db.models.deletion
import traders_blog.models.theory_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0008_alter_levelspotbybit_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=traders_blog.models.theory_models.image_article_path,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="traders_blog.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticlePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="traders_blog.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryTheory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Active"), ("I", "Inactive")],
                        default="I",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="traders_blo_slug_65ca9f_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="traders_blog.categorytheory",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="traders_blo_slug_e83fa3_idx"),
        ),
    ]
