# Generated by Django 5.2.3 on 2025-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "traders_blog",
            "0009_article_articleimage_articlepart_categorytheory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepart",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
