# Generated by Django 5.2.3 on 2025-10-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0010_alter_articlepart_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="traders_blog.articlepart",
            ),
        ),
    ]
