# Generated by Django 5.2.3 on 2025-10-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0011_alter_articleimage_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepart",
            name="slug",
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
