# Generated by Django 5.2.3 on 2025-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders_blog", "0012_articlepart_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
